#!/bin/bash
git add .
git commit -m "his program will assign a random number to the variable n each time it is executed. Complete the source code in order to print the last digit of the number stored in the variable n."
git push
